package com.cuzz.rookiepaybukkit.mapper;

import com.cuzz.rookiepaybukkit.model.doo.OrdersDO;
import com.cuzz.rookiepaybukkit.model.doo.OrdersDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrdersDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    long countByExample(OrdersDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int deleteByExample(OrdersDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int insert(OrdersDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int insertSelective(OrdersDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    List<OrdersDO> selectByExampleWithBLOBs(OrdersDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    List<OrdersDO> selectByExample(OrdersDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    OrdersDO selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int updateByExampleSelective(@Param("row") OrdersDO row, @Param("example") OrdersDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("row") OrdersDO row, @Param("example") OrdersDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int updateByExample(@Param("row") OrdersDO row, @Param("example") OrdersDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int updateByPrimaryKeySelective(OrdersDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(OrdersDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int updateByPrimaryKey(OrdersDO row);
}