package com.cuzz.rookiepaybukkit.mapper;

import com.cuzz.rookiepaybukkit.model.doo.ProductDO;
import com.cuzz.rookiepaybukkit.model.doo.ProductDOExample;
import java.util.List;

import org.apache.ibatis.annotations.CacheNamespace;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.cache.decorators.LruCache;


//implementation：缓存实现类，默认是 PerpetualCache（永久缓存）。
//        eviction：缓存逐出策略（如 LRU - 最近最少使用）。默认是 LRU。
//        size：缓存的最大条目数。
//        readWrite：是否为 读写缓存（true 为读写，false 为只读）。
//        flushInterval：自动刷新缓存的时间间隔（单位：毫秒），默认不会自动刷新。
@CacheNamespace(implementation = org.apache.ibatis.cache.impl.PerpetualCache.class,
        eviction = LruCache.class,
        size = 1024,
        readWrite = true)

public interface ProductDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */

    @Select("SELECT product_name FROM products ")
    List<String> queryAllProductName();

    long countByExample(ProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int deleteByExample(ProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int insert(ProductDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int insertSelective(ProductDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    List<ProductDO> selectByExampleWithBLOBs(ProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    List<ProductDO> selectByExample(ProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    ProductDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int updateByExampleSelective(@Param("row") ProductDO row, @Param("example") ProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int updateByExampleWithBLOBs(@Param("row") ProductDO row, @Param("example") ProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int updateByExample(@Param("row") ProductDO row, @Param("example") ProductDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int updateByPrimaryKeySelective(ProductDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int updateByPrimaryKeyWithBLOBs(ProductDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table products
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    int updateByPrimaryKey(ProductDO row);
}