package com.cuzz.rookiepaybukkit.model.doo;

import java.io.Serializable;

public class OrderProductDO extends OrderProductDOKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_products.product_name
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_products.quantity
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    private Integer quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_products.product_name
     *
     * @return the value of order_products.product_name
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_products.product_name
     *
     * @param productName the value for order_products.product_name
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_products.quantity
     *
     * @return the value of order_products.quantity
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_products.quantity
     *
     * @param quantity the value for order_products.quantity
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}