package com.cuzz.rookiepaybukkit.model.doo;

public class OrderProductDOKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_products.belong_order_number
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    private String belongOrderNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_products.belong_order_number
     *
     * @return the value of order_products.belong_order_number
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    public String getBelongOrderNumber() {
        return belongOrderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_products.belong_order_number
     *
     * @param belongOrderNumber the value for order_products.belong_order_number
     *
     * @mbg.generated Mon Dec 16 09:37:23 CST 2024
     */
    public void setBelongOrderNumber(String belongOrderNumber) {
        this.belongOrderNumber = belongOrderNumber == null ? null : belongOrderNumber.trim();
    }
}